### ISSUE TITLE
Set up API tests in Postman

### ISSUE THREAD

**Issue by spiftire** [0us/IE303911-Klubbhuset#52]

**Comment by markusranda** [comment]
Organization:
- [x] Create new

- [x] Delete

- [x] Get

- [x] Get specific

- [x] Join

- [x] Update

- [x] Get members of specific

- [x] Get managed 

User:
- [x] Create

- [x] Get details of specific

- [x] Delete

Org admin:

- [x] Get all members of specific org

- [x] Check payment status of user

Auth:

- [x] Login

- [x] Logout

- [x] Publickey

Image:

- [ ] Get

**Comment by markusranda** [comment]
Positive Tests:

Organization:
- [x] Create new

- [x] Delete

- [x] Get

- [x] Get specific

- [x] Join

- [x] Update

- [x] Get members of specific

- [x] Get managed 

User:
- [x] Create

- [x] Get details of specific

- [x] Delete

Org admin:

- [x] Get all members of specific org

- [x] Check payment status of user

Auth:

- [x] Login

- [x] Logout

- [x] Publickey

Image:

- [ ] Get  // Not defined path

**Comment by markusranda** [comment]
Tar gjerne forslag tell flere tester.
